name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: sbt
      - run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Check formatting with Scalafmt
        run: sbt scalafmtCheckAll

      - name: Check import organization with Scalafix
        run: sbt "scalafix --check OrganizeImports"

      - name: Run SBT test
        run: sbt test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test

    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: sbt
      - run: sbt publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
