name: Continuous Integration

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: Build and push
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: sbt
      - run: sudo apt-get update && sudo apt-get install -y graphviz
      - run: sbt test
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
      - run: sbt publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
